sudo: false
language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  matrix:
   - DJANGO="Django<1.9"  # 1.8
   - DJANGO="Django<1.10"  # 1.9
   - DJANGO="Django<1.11"  # 1.10
cache:
  directories:
    - $HOME/.cache/pip
install:
 - pip install --upgrade pip
 - pip install "$DJANGO"
 - pip install -r requirements.txt
 - pip install coverage
 - pip install flake8
branches:
 only:
  - master
script:
  - flake8 --exclude=migrations
  - coverage run manage.py test
after_success:
  - coverage report
