sudo: false
language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
env:
  matrix:
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
   - DJANGO="Django<1.11"
cache:
  directories:
    - $HOME/.cache/pip
install:
 - python -m pip install --upgrade pip
 - python -m pip install "$DJANGO"
 - python -m pip install -r requirements.txt
 - python -m pip install flake8 coverage coveralls
branches:
 only:
  - master
script:
  - cp settings.ini.example settings.ini
  - python manage.py makemigrations
  - python manage.py migrate
  - flake8 --exclude=migrations
  - coverage run manage.py test
after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - coveralls
